### PR TITLE
Tesla m3 gate driver

### PR DESCRIPTION
**Pull request by davefiddes**
This PR contains an initial attempt at an SPI driver and integration with stm32-sine of the Tesla Model 3 inverter isolated gate drivers. It is very much an RFC at this stage and will not function as the STM32F103 HW peripheral and GPIO mappings are unknown to me. Feedback most welcome!

### CODE REVIEW

**Comment by davefiddes** [comment]
The build will fail until https://github.com/jsphuebner/libopeninv/pull/1 is merged and a change to update libopeninv pushed to this PR.

**Comment by jsphuebner** [comment]
Will merge this to a new branch for now until it is thoroughly tested.

**Comment by davefiddes** [comment]
Thanks!
I am working on a driver/integration for the Tesla M3 power management/watchdog IC. Should this go on this branch as well?

**Comment by jsphuebner** [comment]
Yes

**Pull request merged**
