### PR TITLE
Make sine output filter "filterConst" a configurable value "sinefilter"

### PR DESCRIPTION
**Pull request by catphish**
I found that the hardcoded output filter on sine ampnom and slip caused an excessive delay to throttle response. This patch makes it a configurable value.

### CODE REVIEW

**Comment by catphish** [comment]
This has been tested on the bench and on the road with my SDU. I am now running my SDU with a reduced value of sinefilter=3.

**Comment by jsphuebner** [comment]
Can you think of a more descriptive name? 
It limits the slew rate of slip frequency and amplitude
Without it, just with throttle ramp, I used to get over current trips and quick throttle changes. Still the case?

**Comment by catphish** [comment]
Looking at the code, this filter protects against two major things that `throtramp` does not, so I think it is still important:
* Negative slew
* Transition from `torque>0` to `torque<0` which would otherwise cause an instant switch from `slip=fslipmin` to `slip=-fslipmin`
* And the same in reverse, `torque<0` to `torque>0`

The problem is that in the case of my vehicle, I found that this filter was much stronger than my desired throtramp, which was quite confusing when configuring things. I ended up setting throtramp to its maximum value and not understanding why I still had a perceived 200ms delay in my throttle response. Making this configurable solves the problem 

This could be renamed to something like `throtfilter` and the documentation could list the approximate slew rate for each value. Arguably this superior filter makes `throtramp` redundant in sine mode, and as I mentioned above, I don't use `throtramp` for this reason.

I can't think of an easy way we could remove either of these parameters though.

**Comment by catphish** [comment]
On an unrelated note, might I suggest you use the "squash and merge" or "rebase and merge" options when accepting pull requests. These will keep the commit history much tidier by not creating additional "merge" commits. The squash option will convert all commits in the pull request into a single commit, which is usually tidier as you end up with one concise commit per feature or change.

**Comment by jsphuebner** [comment]
Yes just change to throtfilter and put it into THROTTLE_PARAMETERS_SINE
Will to the squash and merge

**Pull request merged**
